flask_project/campaign_manager/models/__init__.py
__author__ = 'Irwan Fathurrahman <irwan@kartoza.com>'
__date__ = '17/05/17'

flask_project/campaign_manager/models/json_model.py
__author__ = 'Irwan Fathurrahman <irwan@kartoza.com>'
__date__ = '10/05/17'

from campaign_manager.models.version import Version


class JsonModel(Version):
    """
    Model that use json.
    """
    json_path = ''

    def parse_json_file(self):
        return NotImplemented

    def get_attributes(self):
        """ Get attributes of json model
        :return: attributes
        :rtype: list
        """
        return [
            attr for attr in dir(self)
            if not callable(getattr(self, attr)) and not attr.startswith("_")
            ]

    def to_dict(self):
        """ Return json model as dictionary.
        :return: dict
        """
        dict = {}
        for attribute in self.get_attributes():
            dict[attribute] = getattr(self, attribute)
        dict.pop('json_path')
        dict.pop('geojson_path')
        return dict

    @staticmethod
    class CorruptedFile(Exception):
        def __init__(self):
            self.message = "Json file for this model is corrupted"
            super(JsonModel.CorruptedFile, self).__init__(self.message)

    @staticmethod
    class RequiredAttributeMissed(Exception):
        def __init__(self, attribute):
            self.message = "%s is missed" % attribute
            super(JsonModel.RequiredAttributeMissed,
                  self).__init__(self.message)

flask_project/campaign_manager/models/version.py
__author__ = 'Irwan Fathurrahman <irwan@kartoza.com>'
__date__ = '10/05/17'


class Version(object):
    """
    Version model for tracking versions.
    """
    version = 0.0
    edited_by = ''
    edited_at = ''

flask_project/campaign_manager/forms/__init__.py
__author__ = 'Irwan Fathurrahman <irwan@kartoza.com>'
__date__ = '17/05/17'

flask_project/campaign_manager/forms/campaign.py
__author__ = 'Irwan Fathurrahman <irwan@kartoza.com>'
__date__ = '10/05/17'

from flask_wtf import FlaskForm
from wtforms.fields import (
    DateField,
    SelectField,
    SelectMultipleField,
    StringField,
    SubmitField,
    HiddenField,
    TextAreaField,
    RadioField,
    BooleanField
)
from wtforms.validators import InputRequired, Optional, ValidationError
from urllib.parse import urlparse
from campaign_manager.utilities import get_types
from campaign_manager.views import valid_map_list
from campaign_manager.models.survey import Survey


class ManagerSelectMultipleField(SelectMultipleField):
    def pre_validate(self, form):
        if self.data:
            return True


def validate_map(form, field):
    tile_layer = urlparse(field.data)
    valid_map = valid_map_list()
    if tile_layer.scheme != '' \
            and (tile_layer.netloc != '' or tile_layer.path != ''):
        if tile_layer.scheme != 'https' and field.data not in valid_map:
            raise ValidationError('Please input url using "https://"')
        elif field.data not in valid_map:
            raise ValidationError(
                'The url is invalid or is not supported, please input another '
                'url. e.g. https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png '
                'or leave blank to use default')


class CampaignForm(FlaskForm):
    name = StringField(
        u'Campaign name',
        validators=[InputRequired()],
        description='Name for the campaign',
        render_kw={'placeholder': 'Name of your project'}
    )
    description = TextAreaField(
        u'Campaign description',
        description='Description for the campaign',
        render_kw={'placeholder': 'Describe the type of features that ' +
                   'are being collected and any other participation details.'}
    )
    campaign_status = RadioField(
        u'Campaign status',
        description='Status of the campaign',
        choices=[
            ('Start', 'Start'),
            ('Finish', 'Finish')
        ]
    )
    link_to_omk = BooleanField(
        u'Add button to integrate OpenMapKit'
    )
    start_date = DateField(
        u'Start date of campaign',
        validators=[InputRequired()],
        render_kw={'placeholder': 'Start Date', 'type': 'date'}
    )
    end_date = DateField(
        u'End date of campaign',
        validators=[InputRequired()],
        render_kw={'placeholder': 'End Date', 'type': 'date'}
    )
    campaign_managers = HiddenField(
        u'Project managers',
        validators=[InputRequired()])
    campaign_viewers = HiddenField(
        u'Project viewers'
    )
    campaign_contributors = HiddenField(
        u'Project contributors'
    )
    remote_projects = ManagerSelectMultipleField(
        u'Remote Projects'
    )
    types_options = SelectField(
        u'Types of campaign',
        choices=Survey.to_form(),
        validators=[Optional()]
    )
    types = HiddenField(u'Types that selected for this campaign')
    user_id = HiddenField(u'User id')
    uploader = HiddenField(u'Uploader for this campaign')
    geometry = HiddenField(
        u'Map geometry for this campaign',
        validators=[InputRequired()])
    map_type = StringField(
        u'Campaign Map',
        description='Campaign manager may change the map view',
        validators=[validate_map],
        render_kw={'placeholder': 'Add custom basemap tiles URL. ' +
                   'Use TMS scheme.'}
    )
    selected_functions = HiddenField(
        u'Selected Functions')
    submit = SubmitField(u'Submit')

flask_project/campaign_manager/__init__.py
from flask import Blueprint

campaign_manager = Blueprint(
    'campaign_manager',
    __name__,
    template_folder='templates',
    static_folder='static',
    static_url_path='/static'
)

from campaign_manager import api
from campaign_manager import views

flask_project/campaign_manager/data_providers/__init__.py
__author__ = 'Irwan Fathurrahman <irwan@kartoza.com>'
__date__ = '29/05/17'

flask_project/campaign_manager/insights_functions/__init__.py
__author__ = 'Irwan Fathurrahman <irwan@kartoza.com>'
__date__ = '17/05/17'

from .count_feature import CountFeature
from .feature_attribute_completeness import FeatureAttributeCompleteness
from .mapper_engagement import MapperEngagement
from .osmcha_changesets import OsmchaChangesets
from .osmcha_features import OsmchaFeatures

flask_project/campaign_manager/selected_functions/__init__.py
__author__ = 'Irwan Fathurrahman <irwan@kartoza.com>'
__date__ = '17/05/17'

from .count_feature import CountFeature
from .feature_attribute_completeness import FeatureAttributeCompleteness
from .upload_shapefile import UploadShapefile
from .mapper_engagement import MapperEngagement

flask_project/campaign_manager/views.py
import base64
import csv
import inspect
import json
import os
import hashlib
import requests
import shutil
import operator
from simplekml import Kml, ExtendedData
from datetime import datetime
from flask import jsonify
from shapely import geometry as shapely_geometry

from urllib import request as urllibrequest
from urllib.error import HTTPError, URLError

from bs4 import BeautifulSoup
from flask import (
    request,
    render_template,
    Response,
    abort,
    send_file,
    send_from_directory,
    url_for,
    redirect,
    flash
)

from app_config import Config
from campaign_manager import campaign_manager
from campaign_manager.utilities import (
    get_types,
    map_provider,
    get_allowed_managers,
    parse_json_string
)
import campaign_manager.insights_functions as insights_functions
from campaign_manager.insights_functions._abstract_insights_function import (
    AbstractInsightsFunction
)
from campaign_manager.utilities import temporary_folder
from campaign_manager.data_providers.tasking_manager import \
    TaskingManagerProvider
from campaign_manager.api import CampaignNearestList, CampaignList
from campaign_manager.models.campaign import Campaign, Permission
from campaign_manager.models.survey import Survey
from campaign_manager.insights_functions.osmcha_changesets import \
    OsmchaChangesets

from campaign_manager.data_providers.overpass_provider import OverpassProvider
from reporter import config
from campaign_manager.utilities import (
    load_osm_document_cached, get_contribs, geojson_to_gpx
)
from reporter import LOGGER
from reporter.static_files import static_file
from campaign_manager.aws import S3Data

from xml.sax.saxutils import escape

from flask import session

try:
    from secret import OAUTH_CONSUMER_KEY, OAUTH_SECRET
except ImportError:
    try:
        OAUTH_CONSUMER_KEY = os.environ['OAUTH_CONSUMER_KEY']
        OAUTH_SECRET = os.environ['OAUTH_SECRET']
    except KeyError:
        OAUTH_CONSUMER_KEY = ''
        OAUTH_SECRET = ''

MAX_AREA_SIZE = 320000000


@campaign_manager.route('/')
def home():
    """Landing page

    The first page users land on when they use the app.
    """

    context = dict(
        oauth_consumer_key=OAUTH_CONSUMER_KEY,
        oauth_secret=OAUTH_SECRET,
        map_provider=map_provider()
    )

    return render_template('home.html', **context)


@campaign_manager.route('/learn')
def learn():
    """MapCampaigner Docs

    Information about to use MapCampaigner.
    """

    context = dict(
        oauth_consumer_key=OAUTH_CONSUMER_KEY,
        oauth_secret=OAUTH_SECRET,
        map_provider=map_provider()
    )

    return render_template('learn.html', **context)


@campaign_manager.route('/styleguide')
def styleguide():
    """Styleguide

    This page shows a library of UI components.
    """

    context = dict(
        oauth_consumer_key=OAUTH_CONSUMER_KEY,
        oauth_secret=OAUTH_SECRET,
        map_provider=map_provider()
    )

    return render_template('styleguide.html', **context)


@campaign_manager.route('/user/<osm_id>')
def campaigns_list(osm_id):
    """List the user's campaigns

    A summary campaign manager view with all the users campaigns
    """

    context = dict(
        oauth_consumer_key=OAUTH_CONSUMER_KEY,
        oauth_secret=OAUTH_SECRET,
        all=True,
        map_provider=map_provider(),
        bucket_url=S3Data().bucket_url(),
        osm_id=osm_id
    )

    return render_template('campaign_index.html', **context)


def clean_argument(args):
    """Clean argument that is ImmutableMultiDict to dict
    and clean it's value
    :param args: Argument from request
    :type args: ImmutableMultiDict

    :type: clean argument
    :rtype: dict
    """

    arguments = dict(args)
    clean_arguments = {}
    for key, value in arguments.items():
        if len(value) == 1:
            value = value[0]
        clean_arguments[key] = value
    return clean_arguments


@campaign_manager.route('/campaign/<uuid>/<insight_function_id>')
def get_campaign_insight_function_data(uuid, insight_function_id):
    """Get campaign insight function data.
    """
    return Response("", 200)


@campaign_manager.route('/campaign/osmcha_errors/<uuid>')
def get_osmcha_errors_function(uuid):
    try:
        campaign = Campaign.get(uuid)
        rendered_html = campaign.render_insights_function(
            insight_function_id='total-osmcha-errors',
            insight_function_name='OsmchaChangesets',
            additional_data=clean_argument(request.args)
        )
        return Response(rendered_html)
    except Campaign.DoesNotExist:
        abort(404)


@campaign_manager.route('/campaign/osmcha_errors_data/<uuid>')
def get_osmcha_errors_data(uuid):
    try:
        campaign = Campaign.get(uuid)
        page_size = request.args.get('page_size', None)
        page = request.args.get('page', None)
        osmcha_changeset = OsmchaChangesets(campaign=campaign)

        if page_size:
            osmcha_changeset.max_page = int(page_size)
        if page:
            osmcha_changeset.current_page = int(page)

        osmcha_changeset.run()
        data = osmcha_changeset.get_function_data()
        return jsonify(data)
    except Campaign.DoesNotExist:
        abort(404)


def check_geojson_is_polygon(geojson):
    """Checking geojson is polygon"""
    types = ["Polygon", "MultiPolygon"]
    for feature in geojson['features']:
        if feature['geometry'] and feature['geometry']['type'] not in types:
            return False
    return True


@campaign_manager.route('/campaign/<uuid>/boundary-upload-success')
def campaign_boundary_upload_chunk_success(uuid):
    """Upload chunk handle success.
    """
    from campaign_manager.data_providers.shapefile_provider import \
        ShapefileProvider
    # validate boundary
    try:
        # folder for this campaign
        folder = os.path.join(
            temporary_folder(),
            uuid
        )
        shapefile_file = "%s/%s.shp" % (
            folder, uuid
        )
        geojson = ShapefileProvider().get_data(shapefile_file)

        if len(geojson['features']) > 1:
            # TODO : Check if polygons unionable
            pass

        if geojson['features'][0]['geometry']['type'] != 'Polygon':
            raise ShapefileProvider.MultiPolygonFound

        if not geojson:
            if os.path.exists(folder):
                shutil.rmtree(folder)
            return Response(json.dumps({
                'success': False,
                'reason': 'Shapefile is not valid.'
            }))
        if not check_geojson_is_polygon(geojson):
            if os.path.exists(folder):
                shutil.rmtree(folder)
            return Response(json.dumps({
                'success': False,
                'reason': 'It is not in polygon/multipolygon type.'
            }))

        if os.path.exists(folder):
            shutil.rmtree(folder)
        return Response(json.dumps({
            'success': True,
            'data': geojson,
        }))
    except Campaign.DoesNotExist:
        abort(404)
    except ShapefileProvider.MultiPolygonFound as e:
        return Response(json.dumps({
            'success': False,
            'reason': e.message
        }))


def upload_chunk(_file, filename):
    """Upload chunk file for specific folder.
    :param _file: file to be saved

    :param filename:filename path to be saved
    :type filename: src
    """

    # save uploaded file
    if 'Content-Range' in request.headers:
        range_str = request.headers['Content-Range']
        start_bytes = int(range_str.split(' ')[1].split('-')[0])
        # remove old file if upload new file
        if start_bytes == 0:
            if os.path.exists(filename):
                os.remove(filename)

        # append chunk to the file on disk, or create new
        with open(filename, 'ab') as f:
            f.seek(start_bytes)
            f.write(_file.read())

    else:
        # this is not a chunked request, so just save the whole file
        _file.save(filename)

    # send response with appropriate mime type header
    return Response(json.dumps({
        "name": _file.filename,
        "size": os.path.getsize(filename),
        "url": 'uploads/' + _file.filename,
        "thumbnail_url": None,
        "delete_url": None,
        "delete_type": None
    }))


@campaign_manager.route(
    '/campaign/<uuid>/coverage-upload-chunk',
    methods=['POST'])
def campaign_coverage_upload_chunk(uuid):
    """Upload chunk handle.
    """
    try:
        _file = request.files['file']
        filename = _file.filename
        filenames = os.path.splitext(filename)
        # folder for this campaign
        filename = os.path.join(
            Config.campaigner_data_folder,
            'coverage',
            uuid
        )
        if not os.path.exists(filename):
            os.mkdir(filename)

        # filename of coverage
        filename = os.path.join(
            filename,
            '%s%s' % (
                uuid,
                filenames[1] if len(filenames) > 1 else ''
            )
        )
        return upload_chunk(_file, filename)
    except Campaign.DoesNotExist:
        abort(404)


@campaign_manager.route(
    '/campaign/<uuid>/boundary-upload-chunk',
    methods=['POST'])
def campaign_boundary_upload_chunk(uuid):
    """Upload chunk handle.
    """
    try:
        _file = request.files['file']
        filename = _file.filename
        filenames = os.path.splitext(filename)
        # folder for this campaign
        filename = os.path.join(
            temporary_folder(),
            uuid
        )
        if not os.path.exists(filename):
            os.mkdir(filename)

        # filename of coverage
        filename = os.path.join(
            filename,
            '%s%s' % (
                uuid,
                filenames[1] if len(filenames) > 1 else ''
            )
        )
        return upload_chunk(_file, filename)
    except Campaign.DoesNotExist:

flask_project/campaign_manager/templates/components/feature_tile.html
<div class="row">
  <div class="col-xs-12">
    <div class="panel panel-tile">
      <div class="container-fluid">
        <div class="row">
          <div class="col-xs-12">
            <h4 class="panel-name">
                {% if feature_templates[feature]['element_type'] and feature_templates[feature]['element_type'].lower() == 'polygon' %}
                {% include 'svgs/polygon.html' %}
                {% elif feature_templates[feature]['element_type'] and feature_templates[feature]['element_type'].lower() == 'point' %}
                {% include 'svgs/point.html' %}
                {% else %}
                {% include 'svgs/point.html' %}
                {% endif %}
              {{ feature }}
            </h4>
            <p class="panel-info">{{feature_templates[feature]['feature']}}</p>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 row-tags-wrapper">
            <div class="row-tags">
              {% for tag in feature_templates[feature]['tags'] %}
              {% set subtags = feature_templates[feature]['tags'][tag] %}
                <span class="label label-default" title="{{tag}}{% if subtags %}: {{ subtags|join(', ') }}{% endif %}">
                  {{tag}}{% if subtags %}: {{ subtags|join(', ') }}{% endif %}
                </span>
              {% endfor %}
            </div>
          </div>
        </div>
        <div class="row panel-footer-row">
          <div class="panel-footer">
            <button class="btn btn-sm btn-primary pull-right" onclick="addTypes('{{ feature }}')">Add</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

flask_project/campaign_manager/templates/components/header.html
{% set navigation_items = [
  (url_for('campaign_manager.home'), 'home', 'Home'),
  (url_for('campaign_manager.learn'), 'learn', 'Learn'),
  (url_for('campaign_manager.campaigns_list', osm_id=0), 'projects', 'My Projects')
] -%}

{% set active_page = active_page|default('home') -%}
{% from 'components/page_header.html' import page_header -%}

<div class="panel panel-pagetop">
  <div class="container container-fluid">
    <div class="panel-body">
      Mapping our world together
      <a class="pull-right" href="https://hotosm.org">
        hotosm.org
        {% include 'svgs/link.html' %}
      </a>
    </div>
  </div>
</div>
<nav class="navbar navbar-default">
  <div class="container container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{url_for('campaign_manager.home')}}">
        <img alt="HOTOSM Logo" height="27" src="/static/img/hot-logo.svg">
      </a>
      <p class="navbar-text">Map Campaigner</p>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-left">
        {% for href, id, text in navigation_items %}
        <li {% if id == active_page %}class="active" {% endif %}>
          <a href="{{ href|e }}" id="nav-{{id}}">{{ text|e }}</a>
        </li>
        {% endfor %}
        {% if active_page == "styleguide" %}
        <li class="active">
          <a href="{{ url_for('campaign_manager.styleguide') }}">Styleguide</a>
        </li>
        {% endif %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#" class="create-campaign-button">Create</a></li>
        <li id="login-button" class="login-button"><a class="btn btn-info btn-sm" href="#">Log In</a></li>
        <li id="user-menu" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <span id="profile-name"></span> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu dropdown-user">
            <li id="logout-button">
              <a class="" href="#">
                {% include 'svgs/door.html' %}
                Log Out
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% if page_title is defined %}
{{ page_header(page_title) }}
{% endif %}

flask_project/campaign_manager/templates/components/page_header.html
{%- macro page_header(title='Untitled Page') -%}

<div class="jumbotron page-header">

  {% with messages = get_flashed_messages() %}
         {% if messages %}
               {% for message in messages %}
               <div class="alert alert-success alert-dismissible show" role="alert">
                 <strong>{{ message }}</strong>
               <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                 <span aria-hidden="true">&times;</span>
               </button>
               </div>
               {% endfor %}
         {% endif %}
  {% endwith %}

  <div class="container container-fluid">
    <h1>{{title}}</h1>
  </div>
</div>
{%- endmacro %}

flask_project/campaign_manager/templates/components/small_footer.html
<footer class="small-footer">
  <div class="container container-fluid">
    <div class="row">
      <div class="col-xs-12 col-md-8">
        <a class="pull-left" href="https://www.hotosm.org/contact">Built by Humanitarian OpenStreetMap Team, a 501(c)(3) not-for-profit organization and global community.</a>
      </div>
      <div class="col-xs-12 col-md-4">
        <a class="pull-right" href="https://github.com/hotosm/MapCampaigner/">
          Contribute
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
            <path fill="#FFF" fill-rule="nonzero" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z" />
          </svg>
        </a>
      </div>
    </div>
  </div>
  <div id="optout-form">
    <!-- Used by https://cdn.hotosm.org/tracking-v1.js for cookies prompt -->
  </div>
</footer>